In [5]:
# 
#          Numpy 
# 

import numpy as np 
import time

print() 
t0 = time.process_time() 
print("CPU start time ' ", t0)

n = 5000000 # 5 million 

list1 = list(range(n)) # Create a list with 21 items - n = 0 to 20 
list2 = list(range(n)) # Create a list with 21 items - n = 0 to 20 

t1 = time.process_time() 

delta_time = t1 - t0 

print()
print("The CPU time = ", delta_time) 
print() 





CPU start time '  3.95534

The CPU time =  0.23127399999999954



In [6]:
# 
#          Numpy 
# 

import numpy as np 
import time

print() 
t0 = time.process_time() 

n = 1000000
myArray1 = np.arrange(n)

print() 
t1 = time.time()
delta_time = t1 - t0

print("Wall-Clock end time ' ", t0)
print("Wall-Clock execution time ' ", delta_time)
print()


AttributeError: module 'numpy' has no attribute 'arrange'

In [15]:
# 
# 
#

# print(dir(), end=" ")

print() 
a = np.array( [1, 2, 3, 4, 5] )
print("Array(a) = ", a) 
print() 

b = np.array( [1, 2, 3.0, 4, 5] ) 
print("Array(b) = ", b) 
print() 
print(type(b[1]))
print()




Array(a) =  [1 2 3 4 5]

Array(b) =  [1. 2. 3. 4. 5.]

<class 'numpy.float64'>



In [18]:
# 
#                    multi-dimensional array 
# 

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 3 rows and 3 columns matrix
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
